
name: offerly
description: A simple app to get supmerarket offers.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  html: ^0.15.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.2
  google_fonts: ^6.1.0
  url_launcher: ^6.2.5
  intl: ^0.19.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
